services:
  immich_postgres:
    image: postgres:15
    container_name: immich_postgres
    environment:
      POSTGRES_USER: immich
      POSTGRES_PASSWORD: immich
      POSTGRES_DB: immich
    command: >
      postgres
      -c shared_preload_libraries=vectorchord.so
      -c shared_buffers=128MB
      -c work_mem=4MB
      -c maintenance_work_mem=32MB
      -c max_connections=50
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  immich_redis:
    image: redis:7
    container_name: immich_redis
    command: redis-server --appendonly yes --save 60 1 --maxmemory 256mb --maxmemory-policy noeviction
    volumes:
      - ./redisdata:/data
    ports:
      - "6379:6379"

  immich_api:
    image: ghcr.io/immich-app/immich-api:2.5.6
    container_name: immich_api
    environment:
      DATABASE_HOST: immich_postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: immich
      DATABASE_PASSWORD: immich
      DATABASE_NAME: immich
      REDIS_HOST: immich_redis
      REDIS_PORT: 6379
      APP_PORT: 2283
    depends_on:
      - immich_postgres
      - immich_redis
    ports:
      - "2283:2283"

  immich_microservices:
    image: ghcr.io/immich-app/immich-microservices:2.5.6
    container_name: immich_microservices
    environment:
      DATABASE_HOST: immich_postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: immich
      DATABASE_PASSWORD: immich
      DATABASE_NAME: immich
      REDIS_HOST: immich_redis
      REDIS_PORT: 6379
    depends_on:
      - immich_postgres
      - immich_redis